Fix for numpy array copy with incompatable data types.
I get the error shown below when running the original code:
The fix required only a single line change in two files.

TypeError: Cannot cast ufunc multiply output from dtype('float64') to
dtype('int16') with casting rule 'same_kind'
Traceback (most recent call last):
  File "LiveFFTwithTuner.py", line 187, in handleNewData
    dF=1)
  File "LiveFFTwithTuner.py", line 204, in compute_pitch_hps
    x *= np.hamming(x.size)